#!/bin/bash -e

#set -x

# alias
SSH="sshpass -p m4s3p ssh -q -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no"

run_remote_command() {
    $SSH hexagon@master "$@" > /dev/null 2>&1
}

log_progres()
{
    echo -e "\033[0;32m$*\033[0m" 1>&2
}

log_error()
{
    echo -e "\033[0;31m$*\033[0m" 1>&2
}

fatal()
{
    log_error "ERROR: $*" 1>&2
    exit 1
}

cd "$(dirname "$0")"
SCRIPT_PATH=$(pwd)
VERSION=$(cd .. && basename "$(pwd)")
SQFS_INSTALLER_SCRIPT="/usr/sbin/mining_app_install"
SQFS_FILES=$(ls *.sqfs) || fatal "No sqfs files to install."

log_progres "Installing version \"$VERSION\""
log_progres "SQFS files to install:"
echo $SQFS_FILES

for sqfs in $SQFS_FILES; do
    log_progres "Installing $sqfs"
    if [ -z "${sqfs##*-jspanel-all-*}" ] ;then
        run_remote_command rm -rf /tmp/jspanel-install
        run_remote_command mkdir -p /tmp/jspanel-install
        sshpass -p m4s3p scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $sqfs hexagon@master:/tmp/jspanel-install
        run_remote_command sudo $SQFS_INSTALLER_SCRIPT /tmp/jspanel-install/$sqfs
    else
        sudo $SQFS_INSTALLER_SCRIPT $sqfs ||
            fatal "Failed to install $sqfs on destination."
    fi
done

log_progres "Done."